#name: Deploy To EC2
#on:
#  push:
#    branches:
#      - DH
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Github Repository 파일 불러오기
#        uses: actions/checkout@v4
#      - name: AWS Resource에 접근할 수 있게 AWS credentials 설정
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          aws-region: ap-northeast-2
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      - name: ECR에 로그인하기
#        id: login-ecr
#        uses: aws-actions/amazon-ecr-login@v2
#      - name: Docker 이미지 생성
#        run: docker build -t board-client .
#      - name: Docker 이미지에 Tag 붙이기
#        run: docker tag board-client:latest 911167900973.dkr.ecr.ap-northeast-2.amazonaws.com/board-client
#      - name: ECR에 Docker 이미지 Push하기
#        run: docker push 911167900973.dkr.ecr.ap-northeast-2.amazonaws.com/board-client
#      - name: SSH로 EC2에 접속하기
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ${{ secrets.EC2_USERNAME }}
#          key: ${{ secrets.EC2_PRIVATE_KEY }}
#          script_stop: true
#          script: |
#            docker stop my-client || true
#            docker rm my-client || true
#            docker pull 911167900973.dkr.ecr.ap-northeast-2.amazonaws.com/board-client:latest
#            docker run -d --name my-client -p 3000:3000 911167900973.dkr.ecr.ap-northeast-2.amazonaws.com/board-client:latest